# Generated by Django 5.0.7 on 2024-08-14 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('cve_alumno', models.IntegerField()),
                ('matricula', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateTimeField()),
                ('status', models.CharField(max_length=2)),
                ('generacion', models.CharField(blank=True, max_length=6, null=True)),
                ('status_academico', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'alumno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('cve_carrera', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('abreviatura', models.CharField(blank=True, max_length=3, null=True)),
                ('activo', models.BooleanField()),
                ('fecha_registro', models.DateTimeField()),
            ],
            options={
                'db_table': 'carrera',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('cve_ciudad', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('lada', models.IntegerField()),
            ],
            options={
                'db_table': 'ciudad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('cve_clase', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'clase',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('cve_docente', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('activo', models.BooleanField()),
                ('tipo', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'docente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EspecialidadCarrera',
            fields=[
                ('cve_especialidad', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('cve_carrera', models.SmallIntegerField()),
                ('nombre', models.CharField(max_length=200)),
                ('activo', models.BooleanField()),
                ('abreviatura', models.CharField(max_length=5)),
                ('fecha_registro', models.DateTimeField()),
            ],
            options={
                'db_table': 'especialidad_carrera',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('cve_estado', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('abreviatura', models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                'db_table': 'estado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('cve_estado_civil', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'estado_civil',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('cve_grupo', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('cve_especialidad', models.SmallIntegerField()),
                ('nombre', models.CharField(max_length=10)),
                ('numero_cuatrimestre', models.SmallIntegerField()),
                ('cve_turno', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'grupo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GrupoSeguridad',
            fields=[
                ('cve_grupo_seguridad', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('tiempo_sesion', models.IntegerField()),
                ('activo', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Grupo Seguridad',
                'verbose_name_plural': 'Grupo Seguridad',
                'db_table': 'grupo_seguridad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MateriaPlanEstudio',
            fields=[
                ('cve_materia', models.IntegerField(primary_key=True, serialize=False)),
                ('no_cuatrimestre', models.SmallIntegerField()),
                ('no_unidades', models.IntegerField()),
                ('folio_materia', models.CharField(max_length=20)),
                ('no_horas_semana', models.FloatField(blank=True, null=True)),
                ('integradora', models.BooleanField(blank=True, null=True)),
                ('estadia', models.BooleanField(blank=True, null=True)),
                ('extracurricular', models.BooleanField()),
                ('faltas', models.IntegerField()),
            ],
            options={
                'db_table': 'materia_plan_estudio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('cve_periodo', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('fecha_inicio_clases', models.DateTimeField()),
                ('fecha_fin_clases', models.DateTimeField()),
                ('numero_periodo', models.IntegerField()),
                ('no_extras', models.IntegerField(blank=True, null=True)),
                ('activo', models.BooleanField()),
            ],
            options={
                'db_table': 'periodo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('cve_pais', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('nacionalidad', models.CharField(max_length=40)),
                ('abreviatura', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'pais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('cve_persona', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('apellido_paterno', models.CharField(blank=True, max_length=40, null=True)),
                ('apellido_materno', models.CharField(blank=True, max_length=40, null=True)),
                ('mail', models.CharField(blank=True, max_length=60, null=True)),
                ('movil', models.CharField(blank=True, max_length=20, null=True)),
                ('rfc', models.CharField(max_length=15)),
                ('curp', models.CharField(blank=True, max_length=18, null=True)),
                ('sexo', models.CharField(max_length=1)),
                ('fecha_nacimiento', models.DateTimeField()),
            ],
            options={
                'db_table': 'persona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlanEstudio',
            fields=[
                ('cve_plan_estudio', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
                ('fecha_inicio', models.DateTimeField()),
                ('tipo', models.CharField(max_length=1)),
                ('nomenclatura', models.CharField(max_length=5)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('punto_de_pase', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'plan_estudio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReferenciasBanco',
            fields=[
                ('cve_referencia', models.BigAutoField(primary_key=True, serialize=False)),
                ('concepto', models.CharField(blank=True, max_length=255, null=True)),
                ('matricula', models.CharField(blank=True, max_length=255, null=True)),
                ('accion', models.CharField(blank=True, max_length=255, null=True)),
                ('referencia', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('banco_emisor', models.CharField(blank=True, max_length=255, null=True)),
                ('servicio_bb', models.CharField(blank=True, max_length=255, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('forma_pago', models.CharField(blank=True, max_length=255, null=True)),
                ('monto_parcial_minimo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('firma', models.TextField(blank=True, null=True)),
                ('estatus', models.CharField(blank=True, max_length=255, null=True)),
                ('mensaje', models.CharField(blank=True, max_length=255, null=True)),
                ('monto_original', models.DecimalField(decimal_places=2, max_digits=8)),
                ('recargo_aplicado', models.DecimalField(decimal_places=2, max_digits=8)),
                ('descuento_aplicado', models.DecimalField(decimal_places=2, max_digits=8)),
                ('monto_a_pagar', models.DecimalField(decimal_places=2, max_digits=8)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('no_recibo', models.CharField(blank=True, max_length=255, null=True)),
                ('folio_pago', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_limite_pago', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_pago', models.CharField(blank=True, max_length=10, null=True)),
                ('hora_pago', models.CharField(blank=True, max_length=16, null=True)),
                ('folio_reverso', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_reverso', models.CharField(blank=True, max_length=10, null=True)),
                ('hora_reverso', models.CharField(blank=True, max_length=16, null=True)),
                ('cve_periodo', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_actualizacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'referencias_banco',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cve_persona', models.IntegerField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('activo', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Usuario SITO',
                'verbose_name_plural': 'Usuarios SITO',
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AlumnoClase',
            fields=[
                ('matricula', models.OneToOneField(db_column='matricula', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Sistema.alumno')),
                ('cve_status', models.SmallIntegerField(blank=True, null=True)),
                ('calificacion_final', models.FloatField()),
            ],
            options={
                'db_table': 'alumno_clase',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AlumnoGrupo',
            fields=[
                ('matricula', models.OneToOneField(db_column='matricula', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Sistema.alumno')),
            ],
            options={
                'db_table': 'alumno_grupo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MateriaPlanPeriodo',
            fields=[
                ('cve_periodo', models.OneToOneField(db_column='cve_periodo', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Sistema.periodo')),
            ],
            options={
                'db_table': 'materia_plan_periodo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioGrupoSeguridad',
            fields=[
                ('cve_persona', models.OneToOneField(db_column='cve_persona', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Sistema.usuario')),
            ],
            options={
                'verbose_name': 'Usuario Grupo Seguridad',
                'verbose_name_plural': 'Usuario Grupo Seguridad',
                'db_table': 'usuario_grupo_seguridad',
                'managed': False,
            },
        ),
    ]
